name: LyttleGravestone
version: '${projectVersion}'
main: com.lyttledev.LyttleGravestone
api-version: '1.20'
authors:
  - ThatsATim
  - Stualyttle

dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
      join-classpath: true